# Generated by Django 4.2.2 on 2024-04-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_oa_workflow', '0004_oauserinfo_dept_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRMDepartment',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('DEPARTMENTNAME', models.CharField(max_length=200, verbose_name='部门名称')),
            ],
            options={
                'verbose_name': 'OA部门',
                'verbose_name_plural': 'OA部门',
                'db_table': 'ECOLOGY"."HRMDEPARTMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HRMResource',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('LASTNAME', models.CharField(max_length=200, verbose_name='姓名')),
            ],
            options={
                'verbose_name': 'OA人员',
                'verbose_name_plural': 'OA人员',
                'db_table': 'ECOLOGY"."HRMRESOURCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowBase',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('WORKFLOWNAME', models.CharField(blank=True, max_length=300, null=True, verbose_name='流程名称')),
                ('FORMID', models.IntegerField(verbose_name='表单ID')),
                ('WORKFLOWTYPE', models.IntegerField(verbose_name='所属路径ID')),
                ('ISVALID', models.IntegerField(verbose_name='生效信息')),
                ('VERSION', models.IntegerField(null=True, verbose_name='版本')),
                ('ISTEMPLATE', models.CharField(max_length=10, null=True, verbose_name='是否为流程模板')),
                ('TEMPLATEID', models.IntegerField(null=True, verbose_name='模板ID')),
                ('ACTIVEVERSIONID', models.IntegerField(null=True, verbose_name='当前流程所属活动版本id')),
            ],
            options={
                'verbose_name': 'OA流程信息',
                'verbose_name_plural': 'OA流程信息',
                'db_table': 'ECOLOGY"."WORKFLOW_BASE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowCurrentOperator',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('USERTYPE', models.IntegerField(null=True, verbose_name='用户类型(1、人力资源; 2、客户)')),
                ('VIEWTYPE', models.IntegerField(choices=[(-2, '已查看过流程，不显示任何new标记'), (-1, '查看过流程后又有新的未查看回复，显示黄色new标记'), (0, '接收到流程且未查看过，显示红色new标记')], null=True, verbose_name='查看标志')),
                ('ISREMARK', models.IntegerField(choices=[(0, '未操作'), (1, '转发'), (2, '已操作'), (4, '归档'), (5, '超时'), (6, '自动审批(审批中)'), (8, '抄送(不需提交)'), (9, '抄送(需提交)'), (11, '传阅')], null=True, verbose_name='操作类型')),
                ('ISLASTTIMES', models.IntegerField(null=True)),
                ('ISREJECT', models.CharField(blank=True, max_length=100, null=True, verbose_name='是否为退回前的节点操作人')),
                ('ISBEREJECT', models.CharField(blank=True, max_length=100, null=True, verbose_name='是否退回')),
                ('RECEIVEDATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='接收日期')),
                ('RECEIVETIME', models.CharField(blank=True, max_length=200, null=True, verbose_name='接收时间')),
                ('VIEWDATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='查看日期')),
                ('VIEWTIME', models.CharField(blank=True, max_length=200, null=True, verbose_name='查看时间')),
                ('FIRSTVIEWDATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='初次查看日期')),
                ('FIRSTVIEWTIME', models.CharField(blank=True, max_length=200, null=True, verbose_name='初次查看时间')),
                ('OPERATEDATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='操作日期')),
                ('OPERATETIME', models.CharField(blank=True, max_length=200, null=True, verbose_name='操作时间')),
                ('NODEID', models.IntegerField(null=True)),
                ('AGENTORBYAGENTID', models.IntegerField(null=True)),
                ('AGENTTYPE', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'OA流程当前请求人',
                'verbose_name_plural': 'OA流程当前请求人',
                'db_table': 'ECOLOGY"."WORKFLOW_CURRENTOPERATOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeBase',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NODENAME', models.CharField(blank=True, max_length=300, null=True, verbose_name='节点名称')),
                ('ISSTART', models.CharField(max_length=10, verbose_name='是否创建节点')),
                ('ISREJECT', models.CharField(max_length=10, verbose_name='当前节点是否可以退回')),
                ('ISREOPEN', models.CharField(max_length=10, verbose_name='是否重新打开')),
                ('ISEND', models.CharField(max_length=10, verbose_name='是否归档节点')),
            ],
            options={
                'verbose_name': 'OA流程节点基础信息',
                'verbose_name_plural': 'OA流程节点基础信息',
                'db_table': 'ECOLOGY"."WORKFLOW_NODEBASE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowNodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISREJECT', models.CharField(max_length=10, verbose_name='节点是否可退回')),
                ('LINKNAME', models.CharField(max_length=1000, verbose_name='出口名称')),
            ],
            options={
                'verbose_name': 'OA流程节点出口',
                'verbose_name_plural': 'OA流程节点出口',
                'db_table': 'ECOLOGY"."WORKFLOW_NODELINK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowRequestBase',
            fields=[
                ('REQUESTID', models.IntegerField(primary_key=True, serialize=False)),
                ('REQUESTMARK', models.CharField(blank=True, max_length=200, null=True, verbose_name='编号')),
                ('REQUESTNAME', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('STATUS', models.CharField(blank=True, max_length=200, null=True, verbose_name='状态')),
                ('CREATEDATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='创建日期')),
                ('CREATETIME', models.CharField(blank=True, max_length=200, null=True, verbose_name='创建时间')),
                ('LASTOPERATEDATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='最后操作日期')),
                ('LASTOPERATETIME', models.CharField(blank=True, max_length=200, null=True, verbose_name='最后操作时间')),
                ('REQUESTLEVEL', models.CharField(blank=True, max_length=200, null=True, verbose_name='紧急度')),
            ],
            options={
                'verbose_name': 'OA流程信息',
                'verbose_name_plural': 'OA流程信息',
                'db_table': 'ECOLOGY"."WORKFLOW_REQUESTBASE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowRequestLog',
            fields=[
                ('LOGID', models.IntegerField(primary_key=True, serialize=False)),
                ('LOGTYPE', models.CharField(blank=True, choices=[('0', '批准'), ('1', '保存'), ('2', '提交'), ('3', '退回'), ('4', '重新打开'), ('5', '删除'), ('6', '激活'), ('7', '转发'), ('9', '批注'), ('a', '意见征询'), ('b', '意见征询回复'), ('c', '传阅'), ('e', '强制归档'), ('h', '转办'), ('i', '流程干预'), ('j', '转办反馈'), ('r', '撤回'), ('s', '督办'), ('t', '抄送'), ('x', '结束征询'), ('z', '征询转办')], max_length=100, null=True, verbose_name='操作类型')),
                ('OPERATEDATE', models.CharField(blank=True, max_length=200, null=True, verbose_name='操作日期')),
                ('OPERATETIME', models.CharField(blank=True, max_length=200, null=True, verbose_name='操作时间')),
                ('RECEIVEDPERSONS', models.TextField(blank=True, null=True, verbose_name='接收人')),
                ('RECEIVEDPERSONIDS', models.TextField(blank=True, null=True, verbose_name='接收人IDS')),
                ('REMARK', models.TextField(blank=True, null=True, verbose_name='操作备注')),
            ],
            options={
                'verbose_name': 'OA流程操作记录',
                'verbose_name_plural': 'OA流程操作记录',
                'db_table': 'ECOLOGY"."WORKFLOW_REQUESTLOG',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowFlowNode',
            fields=[
                ('NODEORDER', models.IntegerField(verbose_name='顺序')),
                ('NODEID', models.OneToOneField(db_column='NODEID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='drf_oa_workflow.workflownodebase', verbose_name='节点信息')),
            ],
            options={
                'verbose_name': 'OA流程下的节点',
                'verbose_name_plural': 'OA流程下的节点',
                'db_table': 'ECOLOGY"."WORKFLOW_FLOWNODE',
                'managed': False,
            },
        ),
    ]
