# Generated by Django 5.0.3 on 2024-07-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_oa_workflow', '0005_hrmdepartment_hrmresource_workflowbase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('TYPENAME', models.CharField(max_length=1000, verbose_name='目录')),
                ('TYPEDESC', models.CharField(blank=True, max_length=1000, null=True, verbose_name='描述')),
                ('ICONKEY', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ICONKEY')),
                ('DSPORDER', models.IntegerField(blank=True, null=True, verbose_name='顺序')),
                ('UUID', models.CharField(max_length=50, verbose_name='UUID')),
            ],
            options={
                'verbose_name': 'OA流程目录信息',
                'verbose_name_plural': 'OA流程目录信息',
                'db_table': 'ECOLOGY"."WORKFLOW_TYPE',
                'managed': False,
            },
        ),
    ]
