# Generated by Django 5.0.3 on 2024-08-01 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('drf_oa_workflow', '0006_workflowtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRequestWccExtendInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APPROVAL_STATUS', models.SmallIntegerField(choices=[(1, '审批中'), (2, '审批通过'), (3, '审批拒绝')], default=1, verbose_name='审批状态')),
                ('DOC_STATUS', models.SmallIntegerField(choices=[(0, '待提交'), (1, '待生效'), (2, '生效中'), (3, '待失效'), (4, '已失效')], default=1, verbose_name='单据状态')),
                ('SOURCE', models.CharField(blank=True, default='', max_length=100, verbose_name='来源系统')),
            ],
            options={
                'verbose_name': 'OA流程WCC自定义扩展信息',
                'verbose_name_plural': 'OA流程WCC自定义扩展信息',
                'db_table': 'ECOLOGY"."WORKFLOW_REQUEST_WCCEXTENDINFO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegisterWorkflowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='状态')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('workflow_type_id', models.IntegerField(unique=True, verbose_name='OA流程目录ID')),
                ('workflow_type_name', models.CharField(max_length=500, verbose_name='OA流程目录')),
                ('desc', models.CharField(blank=True, default='', max_length=500, verbose_name='描述')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='顺序')),
                ('uuid', models.CharField(blank=True, default='', max_length=100, verbose_name='UUID')),
            ],
            options={
                'verbose_name': '流程目录注册',
                'verbose_name_plural': '流程目录注册',
                'db_table': 'drf_oa_workflow_register_workflow_type',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='状态')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(blank=True, default='', max_length=128, verbose_name='流程编号')),
                ('title', models.CharField(blank=True, default='', max_length=256, verbose_name='流程标题')),
                ('workflow_request_id', models.CharField(max_length=128, verbose_name='OA流程实例ID')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='业务数据ID')),
                ('approval_status', models.SmallIntegerField(choices=[(1, '审批中'), (2, '审批通过'), (3, '审批拒绝')], default=1, verbose_name='审批状态')),
                ('action', models.SmallIntegerField(choices=[(1, '新增'), (2, '变更'), (3, '启用'), (4, '停用'), (5, '作废')], default=1, verbose_name='触发类型')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='流程结束时间')),
                ('front_form_info', models.JSONField(default=dict, null=True, verbose_name='流程表单信息(前端)')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype', verbose_name='业务类型')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '流程审核',
                'verbose_name_plural': '流程审核',
                'db_table': 'drf_oa_workflow_approval',
            },
        ),
        migrations.CreateModel(
            name='ApprovalOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='状态')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('oa_node_id', models.IntegerField(verbose_name='OA流程节点ID')),
                ('operation_type', models.SmallIntegerField(choices=[(0, '不走流程提交'), (1, '提交'), (2, '批准'), (3, '保存'), (4, '转发'), (5, '转发收回'), (6, '转办'), (7, '批注'), (8, '退回'), (9, '撤回'), (10, '意见征询'), (11, '重新提交'), (12, '强制收回'), (13, '删除流程'), (50, '终止')], verbose_name='操作类型')),
                ('remark', models.TextField(blank=True, default='', verbose_name='意见')),
                ('oa_log_id', models.IntegerField(null=True, verbose_name='OA流程审批记录ID')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operations', to='drf_oa_workflow.approval', verbose_name='流程记录')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '流程操作记录',
                'verbose_name_plural': '流程操作记录',
                'db_table': 'drf_oa_workflow_approval_operation',
            },
        ),
        migrations.CreateModel(
            name='RegisterWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='状态')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(blank=True, default='', max_length=128, verbose_name='流程编号')),
                ('name', models.CharField(max_length=128, verbose_name='流程名称')),
                ('workflow_id', models.IntegerField(unique=True, verbose_name='OA流程ID')),
                ('workflow_form_id', models.IntegerField(null=True, verbose_name='OA流程表单ID')),
                ('workflow_main_table', models.CharField(max_length=128, verbose_name='OA流程主表')),
                ('workflow_detail_tables', models.JSONField(blank=True, default=list, verbose_name='OA流程子表')),
                ('is_active_version', models.SmallIntegerField(choices=[(0, '模板或无效'), (1, '是'), (2, '测试'), (3, '历史版本')], null=True, verbose_name='使用版本')),
                ('workflow_version', models.IntegerField(null=True, verbose_name='OA流程版本')),
                ('file_category_id', models.IntegerField(null=True, verbose_name='OA流程附件目录ID')),
                ('order', models.IntegerField(null=True, verbose_name='OA流程顺序')),
                ('remark', models.TextField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('form_permissions', models.JSONField(blank=True, default=dict, null=True, verbose_name='节点表单权限')),
                ('active_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_versions', to='drf_oa_workflow.registerworkflow', to_field='workflow_id', verbose_name='所属活动流程')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drf_oa_workflow.registerworkflow', to_field='workflow_id', verbose_name='父级')),
                ('workflow_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drf_oa_workflow.registerworkflowtype', to_field='workflow_type_id', verbose_name='OA流程所属目录')),
            ],
            options={
                'verbose_name': '流程注册',
                'verbose_name_plural': '流程注册',
                'db_table': 'drf_oa_workflow_register_workflow',
            },
        ),
        migrations.AddField(
            model_name='approval',
            name='register_workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drf_oa_workflow.registerworkflow', verbose_name='流程'),
        ),
        migrations.CreateModel(
            name='RegisterWorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='状态')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('workflow_id', models.IntegerField(verbose_name='OA流程ID')),
                ('node_order', models.IntegerField(verbose_name='OA流程节点顺序')),
                ('node_id', models.IntegerField(unique=True, verbose_name='OA流程节点ID')),
                ('node_name', models.CharField(blank=True, default='', max_length=256, verbose_name='OA流程节点名')),
                ('is_start', models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], default='', max_length=10, verbose_name='开始节点')),
                ('is_reject', models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], default='', max_length=10, verbose_name='IS REJECT')),
                ('is_reopen', models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], default='', max_length=10, verbose_name='IS REOPEN')),
                ('is_end', models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], default='', max_length=10, verbose_name='结束节点')),
                ('form_permissions', models.JSONField(blank=True, default=dict, null=True, verbose_name='节点表单权限')),
                ('register_workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_nodes', to='drf_oa_workflow.registerworkflow', verbose_name='所属流程')),
            ],
            options={
                'verbose_name': '流程节点',
                'verbose_name_plural': '流程节点',
                'db_table': 'drf_oa_workflow_register_workflow_node',
            },
        ),
        migrations.CreateModel(
            name='RegisterWorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='状态')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('from_node_name', models.CharField(blank=True, default='', max_length=256, verbose_name='FROM节点名')),
                ('to_node_name', models.CharField(blank=True, default='', max_length=256, verbose_name='TO节点名')),
                ('link_name', models.CharField(blank=True, default='', max_length=500, verbose_name='流程出口名称')),
                ('register_workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_node_relations', to='drf_oa_workflow.registerworkflow', verbose_name='所属流程')),
                ('from_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='output_edges', to='drf_oa_workflow.registerworkflownode', to_field='node_id', verbose_name='FROM节点ID')),
                ('to_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='input_edges', to='drf_oa_workflow.registerworkflownode', to_field='node_id', verbose_name='TO节点ID')),
            ],
            options={
                'verbose_name': '流程节点关系',
                'verbose_name_plural': '流程节点关系',
                'db_table': 'drf_oa_workflow_register_workflow_edge',
            },
        ),
    ]
