# Generated by Django 5.0.3 on 2024-07-26 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_oa_workflow', '0006_workflowtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAWorkflowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='状态')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('workflow_type_id', models.IntegerField(unique=True, verbose_name='OA流程目录ID')),
                ('workflow_type_name', models.CharField(max_length=500, verbose_name='OA流程目录')),
                ('desc', models.CharField(blank=True, default='', max_length=500, verbose_name='描述')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='顺序')),
                ('uuid', models.CharField(blank=True, default='', max_length=100, verbose_name='UUID')),
            ],
            options={
                'verbose_name': '流程目录注册',
                'verbose_name_plural': '流程目录注册',
                'db_table': 'oa_workflow_type',
            },
        ),
        migrations.CreateModel(
            name='OAWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='状态')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('code', models.CharField(blank=True, default='', max_length=128, verbose_name='流程编号')),
                ('name', models.CharField(max_length=128, verbose_name='流程名称')),
                ('workflow_id', models.IntegerField(unique=True, verbose_name='OA流程ID')),
                ('workflow_form_id', models.IntegerField(null=True, verbose_name='OA流程表单ID')),
                ('workflow_main_table', models.CharField(max_length=128, verbose_name='OA流程主表')),
                ('workflow_detail_tables', models.JSONField(blank=True, default=list, verbose_name='OA流程子表')),
                ('is_active_version', models.SmallIntegerField(choices=[(0, '模板或无效'), (1, '是'), (2, '测试'), (3, '历史版本')], null=True, verbose_name='使用版本')),
                ('workflow_version', models.IntegerField(null=True, verbose_name='OA流程版本')),
                ('file_category_id', models.IntegerField(null=True, verbose_name='OA流程附件目录ID')),
                ('order', models.IntegerField(null=True, verbose_name='OA流程顺序')),
                ('remark', models.TextField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('form_permissions', models.JSONField(blank=True, default={}, null=True, verbose_name='节点表单权限')),
                ('active_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='other_versions', to='drf_oa_workflow.oaworkflow', to_field='workflow_id', verbose_name='所属活动流程')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drf_oa_workflow.oaworkflow', to_field='workflow_id', verbose_name='父级')),
                ('workflow_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drf_oa_workflow.oaworkflowtype', to_field='workflow_type_id', verbose_name='OA流程所属目录')),
            ],
            options={
                'verbose_name': '流程注册',
                'verbose_name_plural': '流程注册',
                'db_table': 'oa_workflow',
            },
        ),
        migrations.CreateModel(
            name='OAWorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='状态')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('workflow_id', models.IntegerField(verbose_name='OA流程ID')),
                ('node_order', models.IntegerField(verbose_name='OA流程节点顺序')),
                ('node_id', models.IntegerField(unique=True, verbose_name='OA流程节点ID')),
                ('node_name', models.CharField(blank=True, default='', max_length=256, verbose_name='OA流程节点名')),
                ('is_start', models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], default='', max_length=10, verbose_name='开始节点')),
                ('is_reject', models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], default='', max_length=10, verbose_name='IS REJECT')),
                ('is_reopen', models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], default='', max_length=10, verbose_name='IS REOPEN')),
                ('is_end', models.CharField(blank=True, choices=[('1', '是'), ('0', '否')], default='', max_length=10, verbose_name='结束节点')),
                ('form_permissions', models.JSONField(blank=True, default={}, null=True, verbose_name='节点表单权限')),
                ('oa_workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flow_nodes', to='drf_oa_workflow.oaworkflow', verbose_name='所属流程')),
            ],
            options={
                'verbose_name': '流程节点',
                'verbose_name_plural': '流程节点',
                'db_table': 'oa_workflow_node',
            },
        ),
        migrations.CreateModel(
            name='OAWorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '无效'), (1, '有效')], default=1, verbose_name='状态')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='删除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='新增时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('from_node_name', models.CharField(blank=True, default='', max_length=256, verbose_name='FROM节点名')),
                ('to_node_name', models.CharField(blank=True, default='', max_length=256, verbose_name='TO节点名')),
                ('link_name', models.CharField(blank=True, default='', max_length=500, verbose_name='流程出口名称')),
                ('oa_workflow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flow_node_relations', to='drf_oa_workflow.oaworkflow', verbose_name='所属流程')),
                ('from_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='output_edges', to='drf_oa_workflow.oaworkflownode', to_field='node_id', verbose_name='FROM节点ID')),
                ('to_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='input_edges', to='drf_oa_workflow.oaworkflownode', to_field='node_id', verbose_name='TO节点ID')),
            ],
            options={
                'verbose_name': '流程节点关系',
                'verbose_name_plural': '流程节点关系',
                'db_table': 'oa_workflow_edge',
            },
        ),
    ]
