# Generated by Django 5.0.3 on 2024-08-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_oa_workflow', '0007_workflowrequestwccextendinfo_registerworkflowtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='register_workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='drf_oa_workflow.registerworkflow', verbose_name='流程'),
        ),
        migrations.AlterField(
            model_name='registerworkflow',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='drf_oa_workflow.registerworkflow', to_field='workflow_id', verbose_name='父级'),
        ),
    ]
