# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.


name: drf-oa-workflow
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and publish to WCC Python package repository
      - uses: JRubics/poetry-publish@v1.17
        with:
          repository_name: "WCC-PYPI"
          repository_url: "https://pypi.wochacha.cn/"
          repository_username: ${{ WCC_PYPI_USERNAME }}
          repository_password: ${{ WCC_PYPI_PASSWORD }}
